### Modifying Data

In [8]:
import pandas as pd
data={
    'Name':['Varshanth','John', 'Alice', 'Bob', 'Eve','Ram','Aditi','Raj','Prem','Simran'],
    'Age':[22, 30, 22, 28, 35, 27, 24, 29, 31, 26],
    'Salary':[90000, 60000, 55000, 70000, 80000, 65000, 72000, 58000, 75000, 62000],
    'Performace_Score':[96, 90, 75, 80, 95, 88, 92, 78, 83, 87]
}
df=pd.DataFrame(data)
df.head()

        Name  Age  Salary  Performace_Score
0  Varshanth   22   90000                96
1       John   30   60000                90
2      Alice   22   55000                75
3        Bob   28   70000                80
4        Eve   35   80000                95

<Strong>Adding a new column</strong>

In [9]:
df['Bonus'] = df['Salary'] * 0.1
df.head()

        Name  Age  Salary  Performace_Score   Bonus
0  Varshanth   22   90000                96  9000.0
1       John   30   60000                90  6000.0
2      Alice   22   55000                75  5500.0
3        Bob   28   70000                80  7000.0
4        Eve   35   80000                95  8000.0

Using insert() method to add a new column at a specific position<br>
df.insert(location, "column_name", data)

In [10]:
df.insert(0,"Employee_ID", range(1, len(df) + 1))
df.head()

   Employee_ID       Name  Age  Salary  Performace_Score   Bonus
0            1  Varshanth   22   90000                96  9000.0
1            2       John   30   60000                90  6000.0
2            3      Alice   22   55000                75  5500.0
3            4        Bob   28   70000                80  7000.0
4            5        Eve   35   80000                95  8000.0

<strong>Updating</strong><br>
.loc[]<br>
df.loc[row_index,"Column_name"] = new_value

In [13]:
df.loc[0,'Salary']= 95000
df.head(2)

   Employee_ID       Name  Age  Salary  Performace_Score   Bonus
0            1  Varshanth   22   95000                96  9000.0
1            2       John   30   60000                90  6000.0

In [14]:
# Increasing salary by 5%
df['Salary'] = df['Salary'] * 1.05
df.head(2)

   Employee_ID       Name  Age   Salary  Performace_Score   Bonus
0            1  Varshanth   22  99750.0                96  9000.0
1            2       John   30  63000.0                90  6000.0

<strong>Deleting Columns</strong><br>
df.drop(columns=["ColumnName"], inplace=True)

In [15]:
df.drop(columns=['Bonus'], inplace=True)
df.head(2)

   Employee_ID       Name  Age   Salary  Performace_Score
0            1  Varshanth   22  99750.0                96
1            2       John   30  63000.0                90