# Handling Missing Data

nan (Not a Number) <br>
None (for object data types)

In [1]:
import pandas as pd
data={
    'Name':['Varshanth',None, 'Alice', 'Bob', 'Eve','Ram','Aditi','Raj','Prem','Simran'],
    'Age':[22, None, 22, 28, 35, 27, 24, 29, 31, 26],
    'Salary':[90000, None, 55000, 70000, 80000, 65000, 72000, 58000, 75000, 62000],
    'Performace_Score':[96, None, 75, 80, 95, 88, 92, 78, 83, 87]
}
df=pd.DataFrame(data)
df.head(2)

        Name   Age   Salary  Performace_Score
0  Varshanth  22.0  90000.0              96.0
1       None   NaN      NaN               NaN

In [3]:
print(df.isnull())
print("Total missing values in each column:")
print(df.isnull().sum())

    Name    Age  Salary  Performace_Score
0  False  False   False             False
1   True   True    True              True
2  False  False   False             False
3  False  False   False             False
4  False  False   False             False
5  False  False   False             False
6  False  False   False             False
7  False  False   False             False
8  False  False   False             False
9  False  False   False             False
Total missing values in each column:
Name                1
Age                 1
Salary              1
Performace_Score    1
dtype: int64

Deleting rows which have missing values<br>

df.dropna(axis=0,inplace=True)<br>
axis=0 -> delete the rows which contain missing values<br>
axis=1 -> delete the columns which contain missing values

In [4]:
df.dropna(axis=0, inplace=True)
df.head(5)

        Name   Age   Salary  Performace_Score
0  Varshanth  22.0  90000.0              96.0
2      Alice  22.0  55000.0              75.0
3        Bob  28.0  70000.0              80.0
4        Eve  35.0  80000.0              95.0
5        Ram  27.0  65000.0              88.0

<strong>Filling missing values</strong><br>
df.fillna(value, inplace=True)

In [ ]:
data={
    'Name':['Varshanth',None, 'Alice', 'Bob', 'Eve','Ram','Aditi','Raj','Prem','Simran'],
    'Age':[22, None, 22, 28, 35, 27, 24, 29, 31, 26],
    'Salary':[90000, None, 55000, 70000, 80000, 65000, 72000, 58000, 75000, 62000],
    'Performace_Score':[96, None, 75, 80, 95, 88, 92, 78, 83, 87]   
}
df=pd.DataFrame(data)
print(df.head(3))

df.fillna(value={'Name':'Unknown', 'Age':df['Age'].mean(), 'Salary':df['Salary'].mean(), 'Performace_Score':df['Performace_Score'].mean()}, inplace=True)
# df["Salary"].fillna(df["Salary"].mean(), inplace=True)
df.head(5)

        Name   Age   Salary  Performace_Score
0  Varshanth  22.0  90000.0              96.0
1       None   NaN      NaN               NaN
2      Alice  22.0  55000.0              75.0

        Name        Age        Salary  Performace_Score
0  Varshanth  22.000000  90000.000000              96.0
1    Unknown  27.111111  69666.666667              86.0
2      Alice  22.000000  55000.000000              75.0
3        Bob  28.000000  70000.000000              80.0
4        Eve  35.000000  80000.000000              95.0

<strong>Interpolasion</strong><br>

in place of missing values fills by predicting the values with realistic number

Predicting methods<br>
linear, polynomial etc

In [6]:
data={
    'Time':[1,2,3,4,5,6,7,8,9,10],
    'Value':[10,12,None,15,14,None,18,20,None,22]
}
df=pd.DataFrame(data)
df["Value"].interpolate(method='linear', inplace=True)
df.head(10)

C:\Users\varshanth\AppData\Local\Temp\ipykernel_30304\1981504797.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Value"].interpolate(method='linear', inplace=True)

   Time  Value
0     1   10.0
1     2   12.0
2     3   13.5
3     4   15.0
4     5   14.0
5     6   16.0
6     7   18.0
7     8   20.0
8     9   21.0
9    10   22.0